### ISSUE TITLE
PDFs from newer Factur-X/ZUGFeRD specification are not supported

### ISSUE THREAD

**Issue by NikolaiMe** [schwarmdigital/factur-x.js#4]
### Misbehavior:
- When using a pdf from the newer specification (e.g. MINIMUM_Rechnung.pdf from spec ZF23_DE) the "interpretation-tests" fail with error message: "could not find factur-x.xml in pdf" although it is clearly there (visible as attachment in adobe acrobat reader)

### Expected behavior:
- factur-x.xml can be also found in pdfs which are conform to a newer specification then ZF22.

### Steps to reproduce:
- Download the ZF23 Specification
- Search for MINIMUM_Rechnung.pdf in folder "ZF23_DE\Beispiele\0. MINIMUM\MINIMUM_Rechnung"
- Replace the ZF22 MINIMUM_Rechnung.pdf in project-folder "test\pdfs" with the ZF23 MINIMUM_Rechnung.pdf
- run "npm run test" --> Test Suites: 1 failed, 1 passed, 2 total --> The failing test-suite fails because the xml is not available.

**Comment by schwarmco** [comment]
Apparently Zugferd 2.3.2 changed the example pdfs to use a UTF-16 encoded "factur\055x\056xml". As there is no mention of that in the specification this is probably not intended although its perfectly valid according to PDF/A-3.
Will push a fix that checks for UTF-16 Byte Order Marks to handle this.
